version: '2.3'

services:
  matchpub:
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
        - user_id=${USER_ID}
        - group_id=${GROUP_ID}
    image: matchpub
    env_file:
    - ./.env
    volumes:
    - ./src:/app/src
    - ./test:/app/test
    - ./data:${DATA}
    - ./results:${RESULTS}
    - ./reports:${REPORTS}
    - ./log:/log
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /tmp:/tmp
    - .config:/.config
    environment:  # xhost + 127.0.0.1; docker-compose run --rm -e DISPLAY=host.docker.internal:0 matchpub
      - XAUTHORITY=${XAUTH} # needs to make sure export XAUTH before i.e. in .bashrc
      - DISPLAY=${DISPLAY} # this seems to be exported by default 
    working_dir: /app
    command: ['python', '-m', 'src.email']